modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Rongmario/CleanCut/issues"
[[mods]]
modId="cleancut"
version="2.1"
displayName="Clean Cut"
displayURL="https://github.com/Rongmario/CleanCut"
logoFile="icon.png"
authors="Rongmario"
description='''
Fight enemies back through grass and other similar obstructions!
'''
